---
- name: disable all redhat repos
  file: path={{ item }} state=absent
  with_fileglob:
      - /etc/yum.repos.d/redhat-*.repo
      - /etc/yum.repos.d/rhui-load-balancers.conf

- name: setup yum repo
  copy:
    content: |
      [rhel-7-server-rpms]
      name=rhel-7-server-rpms
      baseurl=http://{{ ose_repo_server }}/repos/rhel-7-server-rpms
      enabled=1
      gpgcheck=0
      [rhel-7-server-extras-rpms]
      name=rhel-7-server-extras-rpms
      baseurl=http://{{ ose_repo_server }}/repos/rhel-7-server-extras-rpms
      enabled=1
      gpgcheck=0
      [rhel-7-fast-datapath-rpms]
      name=rhel-7-fast-datapath-rpms
      baseurl=http://{{ ose_repo_server }}/repos/rhel-7-fast-datapath-rpms
      enabled=1
      gpgcheck=0
      [rhel-7-server-ose-3.6-rpms]
      name=rhel-7-server-ose-3.6-rpms
      baseurl=http://{{ ose_repo_server }}/repos/rhel-7-server-ose-3.6-rpms
      enabled=1
      gpgcheck=0
    dest: /etc/yum.repos.d/ose.repo
    mode: 0644
    owner: root
    group: root

- name: Update the yum cache
  yum:
    name: '*'
    state: latest
    update_cache: yes

- name: Upgrade all packages
  yum:
    name: '*'
    state: latest
#
- name: Installing Base Packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - wget
    - git
    - net-tools
    - bind-utils
    - iptables-services
    - bridge-utils
    - bash-completion
    - kexec-tools
    - sos
    - psacct
    - docker
    - python-cryptography
    - atomic


- name: Add insecure registry and logs to docker OPTIONS
  replace:
   dest: /etc/sysconfig/docker
   regexp: '^OPTIONS=.*'
   replace: 'OPTIONS="--selinux-enabled --insecure-registry {{ openshift_prepare_services_subnet }} --log-opt max-size={{ openshift_prepare_log_max_size }} --log-opt max-file={{ openshift_prepare_log_max_file }}"'
   backup: yes

#TODO : Disk and VG management
#https://docs.openshift.org/latest/install_config/install/host_preparation.html#configuring-docker-storage
##https://galaxy.ansible.com/mkubenka/docker-storage-setup/
#
- name: configure docker-storage-setup
  copy:
    content: |
      DEVS= {{ openshift_docker_device }}
      VG=docker-vg
    dest: /etc/sysconfig/docker-storage-setup
    mode: 0644
    owner: root
    group: root
- name: setup docker storage
  command: docker-storage-setup

- name: Disable docker service
  service:
    name: docker
    state: stop
    enabled: yes

- name: remove /var/lib/docker/* files
  file: path={{ item }} state=absent
  with_fileglob: /var/lib/docker/*

- name: Enable docker service
  service:
    name: docker
    state: started
    enabled: yes
